import type { Metadata } from "next";

import ButtonsActions from "./_components/buttons-actions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ButtonsActions />
      {children}
    </>
  );
}
